# Generated by Django 5.1.6 on 2025-09-02 07:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
